SELECT * FROM [Dataset for Data Analytics (1)]

SELECT CUSTOMERID,PRODUCT,PAYMENTMETHOD,REFERRALSOURCE 
FROM [Dataset for Data Analytics (1)]

SELECT ORDERID, CUSTOMERID, PRODUCT, TOTALPRICE 
FROM [Dataset for Data Analytics (1)]
WHERE ORDERSTATUS = 'Delivered'

SELECT ORDERID, PRODUCT, TotalPrice
FROM [Dataset for Data Analytics (1)]
WHERE TotalPrice > 1000
ORDER BY TotalPrice DESC 

SELECT PRODUCT, UNITPRICE
FROM [Dataset for Data Analytics (1)]
ORDER BY UnitPrice ASC

SELECT ORDERSTATUS, COUNT(*) AS ORDERCOUNT
FROM [Dataset for Data Analytics (1)]
GROUP BY OrderStatus
ORDER BY ORDERCOUNT DESC

SELECT PRODUCT, SUM(TOTALPRICE) AS TOTALREVENUE
FROM [Dataset for Data Analytics (1)]
GROUP BY Product
ORDER BY TOTALREVENUE DESC

SELECT PRODUCT, AVG(UNITPRICE) AS AVGUNITPRICE
FROM [Dataset for Data Analytics (1)]
GROUP BY Product
ORDER BY AVGUNITPRICE DESC

